movies:
  synop_short: 60
  limit: 5
  name_length: 25
  page: 10
  synopsis_short: 200
  rating:
    score: 4.5
  ratings_round: 1
users:
  page: 2
reviews:
  cont_length: 800
gravatar:
  size: 50
  default_size: 80
min_password_length: 6
max_password_length: 32
